### ISSUE TITLE
Change block header colors

### ISSUE THREAD

**Issue by ai** [browserslist/browserslist-vscode#1]
Now the browser and block section use the same color.

But block header is a very important structural element to understand the context.

It will be better to use a different type for headers.

**Comment by wspwebben** [comment]
I've updated colors for section and config names, what do you think?

![Dark theme](https://user-images.githubusercontent.com/34203719/100541969-f6eb9d00-3279-11eb-95dd-a1c513134664.png)

![Light theme](https://user-images.githubusercontent.com/34203719/100541974-fbb05100-3279-11eb-870d-b58ee80485ec.png)

**Comment by ai** [comment]
Looks good!
