### ISSUE TITLE
Add icons to extension

### ISSUE THREAD

**Issue by ai** [browserslist/browserslist-vscode#2]
I think Browserslist icon will be good here

![20201127162126](https://user-images.githubusercontent.com/19343/100485040-a420b280-30cc-11eb-864c-fa687eb4723c.png)

You can take logo from [our official repo](https://github.com/browserslist/browserslist/blob/master/img/logo.svg).

**Comment by wspwebben** [comment]
Added and icon, thanks

![Screenshot with a new extension icon](https://user-images.githubusercontent.com/34203719/100542348-eb00da80-327b-11eb-89ab-84f97b918da1.png)
