### ISSUE TITLE
Normalize sources

### ISSUE THREAD

**Issue by ai** [browserslist/browserslist-vscode#4]
[One JSON file](https://github.com/browserslist/browserslist-vscode/blob/main/syntaxes/browserslist.tmLanguage.json) uses tabs, [another](https://github.com/browserslist/browserslist-vscode/blob/main/language-configuration.json) spaces.

Possible solution:

1. Add [`.editorconfig`](https://github.com/browserslist/browserslist/blob/master/.editorconfig)
2. Convert all files.

**Comment by wspwebben** [comment]
Fixed format in [fcb6a4a](https://github.com/browserslist/browserslist-vscode/commit/fcb6a4a9ae57d7cc13228626288c76e28a7e9939)

Thanks for feedback!
